### ISSUE TITLE
Error: Cannot autolaunch D-Bus without X11 $DISPLAY

### ISSUE THREAD

**Issue by dprothero** [twilio/twilio-cli#1]
Currently, the [keytar](https://www.npmjs.com/package/keytar) package used for saving credentials locally doesn't work on a headless linux server.

Need a way to save credentials in this scenario. (Just write them to the config file? Rely on environment vars?)

**Comment by joliveros** [comment]
I think a config file at ‘$HOME/.config/twilio-cli/settings.json’ could work. Tools like Atom, VSCode will store user settings there and should be persistent across installations. For instance, a user could remove twilio-cli or reinstall it and the config file will be persistent.

Cheers

**Comment by erperejildo** [comment]
I still getting this error. Any update on the ticket?

**Comment by dprothero** [comment]
@erperejildo Try setting environment variables with your credentials as discussed here:
```
https://www.twilio.com/docs/twilio-cli/general-usage#want-to-use-environment-variables-instead-of-creating-a-profile
```
When you do that, just start using the CLI. You don't have to run `twilio login`

**Comment by gkemp94** [comment]
@dprothero We're still having issue with this, we're setting env variables (opt 2 as specified in your referenced doc) before running the `npm run deploy` command within a flex-plugin (v3) project, the project builds fine but then the deploy fails with the `Cannot autoLaunch D-Bus winthout X11 $DISPLAY` We're running all this on our CI Jenkins Server in AWS.

**Comment by dprothero** [comment]
@gkemp94 can you report what version of the CLI you are running? Have you tried uninstalling and reinstalling the latest release (v1.6.0)?

**Comment by gkemp94** [comment]
Hi David,

Actually we just resolved our issue, we found that setting CI=true skips
loading whatever library or functionality that was being loaded causing
this issue.

Thanks for following up though.

George

**Comment by dprothero** [comment]
@gkemp94 I'm not familiar with a `CI=true` setting. Would you be able to elaborate on the context of that setting and how we think it helped solve the issue?

**Comment by dprothero** [comment]
I think we figured it out with the Flex plugin builder team!

**Comment by alexiuscrow** [comment]
> Actually we just resolved our issue, we found that setting CI=true skips loading whatever library or functionality that was being loaded causing this issue.

It really works with `CI=true`. Can you provide more info about this prop? What package used it?

**Comment by adrianacca** [comment]
@alexiuscrow I've gone through source code of flex-plugin and setting `CI=true` prevents keytar from loading and saving credentials but it will also treat all warnings as errors. I've discovered that issue was caused not by loading keytar package but by saving credentials which can be skipped with `SKIP_CREDENTIALS_SAVING=true` - so if you don't want to treat warnings as errors feel free to use that flag instead.

**Comment by Ken-vdE** [comment]
This issue is not resolved for me (in headless ubuntu:21.04 docker environment):

```
root@91bf6b6a0a58:/var/www/html# twilio login -l debug
[DEBUG] Config File: /root/.twilio-cli/config.json
[DEBUG] Error loading keytar: Error: Cannot autolaunch D-Bus without X11 $DISPLAY
 » Secure credential storage failed to load.

Alternatively, twilio-cli can use credentials stored in environment variables:

# OPTION 1 (recommended)
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_API_KEY=an API Key created at twil.io/get-api-key
export TWILIO_API_SECRET=the secret for the API Key

# OPTION 2
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_AUTH_TOKEN=your Auth Token from twil.io/console

Once these environment variables are set, a twilio-cli profile is not required and you may skip the "login" step.
[DEBUG] TwilioCliError: Secure credential storage failed to load.

Alternatively, twilio-cli can use credentials stored in environment variables:

# OPTION 1 (recommended)
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_API_KEY=an API Key created at twil.io/get-api-key
export TWILIO_API_SECRET=the secret for the API Key

# OPTION 2
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_AUTH_TOKEN=your Auth Token from twil.io/console

Once these environment variables are set, a twilio-cli profile is not required and you may skip the "login" step.
    at SecureStorage.loadKeytar (/usr/lib/node_modules/twilio-cli/node_modules/@twilio/cli-core/src/services/secure-storage.js:35:15)
    at async Login.run (/usr/lib/node_modules/twilio-cli/src/commands/profiles/create.js:34:5)
    at async Login._run (/usr/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/lib/node_modules/twilio-cli/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/usr/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/main.js:27:9)
    at async Main._run (/usr/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/command.js:43:20)
```

or (I have the TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN variables set correctly)

```
root@91bf6b6a0a58:/var/www/html#        twilio profiles:create --profile "project-danger" -l debug
[DEBUG] Config File: /root/.twilio-cli/config.json
[DEBUG] Error loading keytar: Error: Cannot autolaunch D-Bus without X11 $DISPLAY
 » Secure credential storage failed to load.

Alternatively, twilio-cli can use credentials stored in environment variables:

# OPTION 1 (recommended)
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_API_KEY=an API Key created at twil.io/get-api-key
export TWILIO_API_SECRET=the secret for the API Key

# OPTION 2
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_AUTH_TOKEN=your Auth Token from twil.io/console

Once these environment variables are set, a twilio-cli profile is not required and you may skip the "login" step.
[DEBUG] TwilioCliError: Secure credential storage failed to load.

Alternatively, twilio-cli can use credentials stored in environment variables:

# OPTION 1 (recommended)
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_API_KEY=an API Key created at twil.io/get-api-key
export TWILIO_API_SECRET=the secret for the API Key

# OPTION 2
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_AUTH_TOKEN=your Auth Token from twil.io/console

Once these environment variables are set, a twilio-cli profile is not required and you may skip the "login" step.
    at SecureStorage.loadKeytar (/usr/lib/node_modules/twilio-cli/node_modules/@twilio/cli-core/src/services/secure-storage.js:35:15)
    at async Login.run (/usr/lib/node_modules/twilio-cli/src/commands/profiles/create.js:34:5)
    at async Login._run (/usr/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/lib/node_modules/twilio-cli/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/usr/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/main.js:27:9)
    at async Main._run (/usr/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/command.js:43:20)
```
