### ISSUE TITLE
Flex Configuration update API unsupported

### ISSUE THREAD

**Issue by cwkendall** [twilio/twilio-cli#113]
#### Issue Summary

Flex Configuration API has an update operation which accepts a JSON body only.  The Twilio CLI doesn't currently support setting a JSON request body via a command line parameter

#### Steps to Reproduce

1. Attempt to update the Flex Configuration via the Twilio CLI using the command:
`twilio api:flex:v1:configuration:update`

2. Error message is returned (see debug output below)

3. Help does not provide any clue to how a body may be specified.  

Example debug output:
`$ twilio api:flex:v1:configuration:update -l debug
[DEBUG] Config File: /Users/ckendall/.twilio-cli/config.json
[DEBUG] Using profile: Flex Demo
[DEBUG] Provided flags: {"cli-log-level":"debug","properties":"status,uiLanguage,uiVersion,serviceVersion","skip-parameter-validation":false,"cli-output-format":"columns"}
[DEBUG] domainName=flex, path=/v1/Configuration, actionName=update
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] post https://flex-api.twilio.com/v1/Configuration
[DEBUG] Form data:
[DEBUG] {}
[DEBUG] User-Agent: @twilio/cli-core/3.0.3 (twilio-api-client/3.0.3, node.js v10.16.0, darwin 18.7.0 x64, api:flex:v1:configuration:update)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 415
[DEBUG] response.headers: {"date":"Tue, 03 Sep 2019 02:54:07 GMT","content-type":"application/json; charset=utf-8","content-length":"172","connection":"close","twilio-request-id":"RQ420d91eafe9147ff85dd42a480983399","twilio-request-duration":"0.033","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"flex-api.twilio.com","strict-transport-security":"max-age=31536000"}
 » Error code 20415 from Twilio: The server does not support the media type transmitted in the request.. See https://www.twilio.com/docs/errors/20415 for more info.
[DEBUG] TwilioCliError: Error code 20415 from Twilio: The server does not support the media type transmitted in the request.. See https://www.twilio.com/docs/errors/20415 for more info.
    at CliRequestClient.request (/usr/local/Cellar/twilio/1.4.2/libexec/node_modules/@twilio/cli-core/src/services/cli-http-client.js:88:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by childish-sambino** [comment]
The update operation is a JSON API which is not currently supported by the CLI. Leaving open for prioritization. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by thinkingserious** [comment]
Since there has been no activity on this issue since March 1, 2020, we are closing this issue. Please feel free to reopen or create a new issue if you still require assistance. Thank you!
