### ISSUE TITLE
"string.trim is not a function" error when sending sms from cli

### ISSUE THREAD

**Issue by Aidanchase** [twilio/twilio-cli#130]
#### Issue Summary

In twilio cli when attempting to send an sms through twilio api:core, the error string.trim is not a function prevents the sms from sending.

#### Steps to Reproduce

In cli;
 twilio api:core:messages:create \ --to +1416XXXXX \ --from +1434XXXXX \ --body "x" \ -o json

returns: 
 "TypeError: string.trim is not a function at ConfigData.sanitize (/usr/local/Cellar/twilio/1.7.2/libexec/node_modules/@twilio/cli-core/src/services/config.js:143:28)"

#### Technical details:

* `twilio version` output: twilio-cli/1.7.2 darwin-x64 node-v10.16.0
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
TypeError: string.trim is not a function
    at ConfigData.sanitize (/usr/local/Cellar/twilio/1.7.2/libexec/node_modules/@twilio/cli-core/src/services/config.js:143:28)
    at ConfigData.getProfileById (/usr/local/Cellar/twilio/1.7.2/libexec/node_modules/@twilio/cli-core/src/services/config.js:57:26)
    at ConfigData.setActiveProfile (/usr/local/Cellar/twilio/1.7.2/libexec/node_modules/@twilio/cli-core/src/services/config.js:69:28)
    at ConfigData.loadFromObject (/usr/local/Cellar/twilio/1.7.2/libexec/node_modules/@twilio/cli-core/src/services/config.js:138:10)
    at Config.load (/usr/local/Cellar/twilio/1.7.2/libexec/node_modules/@twilio/cli-core/src/services/config.js:160:16)
```

**Comment by childish-sambino** [comment]
Stacktrace points to an issue when loading your profile from the config file (`~/.twilio-cli/config.json`). Do you mind copying the contents here (scrubbed of any SIDs) to help debug?

**Comment by Aidanchase** [comment]
> Stacktrace points to an issue when loading your profile from the config file (`~/.twilio-cli/config.json`). 

I don't seem to have that file in my cloned directory!

**Comment by Aidanchase** [comment]
Here it is: {"email":"aidXXXXXXXX","prompts":{},"projects":[{"id":"ac","accountSid":"ACxxxxxxxxxxx"}],"activeProject": true}

**Comment by Aidanchase** [comment]
Ahh, the problem was solved by replacing "activeProject": true with the default "null". Not sure why I changed that! Thanks for the help!
