### ISSUE TITLE
twilio login returns Could not create an API Key.

### ISSUE THREAD

**Issue by Brodan** [twilio/twilio-cli#134]
#### Issue Summary

`twilio login` returns with `Could not create an API Key.` despite simply copying my account SID and auth token from console and pasting them in.

#### Steps to Reproduce

1. `twilio login`
2. enter nickname for the login such as brodan
3. paste Account SID from Twilio console
4. paste auth token from Twilio console

#### Technical details:

* `twilio version` output: `twilio-cli/1.7.2 darwin-x64 node-v10.16.0`
* `node --version` output: `v12.12.0`
* osx version: `10.14.6`
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
$ twilio login -l debug
[DEBUG] Config File: /Users/christopherhranj/.twilio-cli/config.json
? Shorthand identifier for your profile: brodan
? Account credentials are currently stored in environment variables and will take precedence over the "brodan" profile when connecting to Twilio, unless the "brodan" profile is explicitly specified. Continue setting up "brodan" prof
ile? Yes
You can find your Account SID and Auth Token at https://www.twilio.com/console
 » Your Auth Token will be used once to create an API Key for future CLI access to your Twilio Project, and then forgotten.
? The Account SID for your Twilio Project: ACxxxxxxxxxxxxxxxxxxxx
? Your Twilio Auth Token for your Twilio Project: [hidden]
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://api.twilio.com/2010-04-01/Accounts/ACxxxxxxxxxxxxxxxxxxaee403b545.json
[DEBUG] User-Agent: @twilio/cli-core/4.2.1 (twilio-node/3.36.0, node.js v10.16.0, darwin 18.7.0 x64, login)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Sun, 27 Oct 2019 20:59:15 GMT","content-type":"application/json; charset=utf-8","content-length":"2243","connection":"close","last-modified":"Sat, 26 Oct 2019 19:22:08 +0000","twilio-concurrent-requests":"1","etag":"12e3852eb8df7bcfbb568b1c8a2e575a","twilio-request-id":"RQ3b87e3446ba446e8ae9acc4c37f41bd4","twilio-request-duration":"0.048","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"api.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] POST https://api.twilio.com/2010-04-01/Accounts/ACxxxxxxxxxxxxxxxxxxxaee403b545/Keys.json
[DEBUG] Form data:
[DEBUG] {"FriendlyName":"twilio-cli for christopherhranj on Chris-Hranjs-MacBook-Pro.local"}
[DEBUG] User-Agent: @twilio/cli-core/4.2.1 (twilio-node/3.36.0, node.js v10.16.0, darwin 18.7.0 x64, login)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 400
[DEBUG] response.headers: {"date":"Sun, 27 Oct 2019 20:59:15 GMT","content-type":"application/json; charset=utf-8","content-length":"139","connection":"close","twilio-request-id":"RQ445f344df9814b3cab4dcee28333469c","twilio-request-duration":"0.033","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"api.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] {"name":"TwilioCliError","exitCode":70001}
 » Could not create an API Key.
[DEBUG] TwilioCliError: Could not create an API Key.
    at Login.saveCredentials (/usr/local/Cellar/twilio/1.7.2/libexec/src/commands/profiles/create.js:182:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by childish-sambino** [comment]
Will be fixed by #133

**Comment by childish-sambino** [comment]
Fix will be included in next release which is scheduled for 2019-10-30.

**Comment by Brodan** [comment]
Awesome! Thanks for the quick turn-around and explanation! Happy to know the reason why it wasn't working, that was the most frustrating part!
