### ISSUE TITLE
Parameter validation is failing on Trunk_SID's beginning in TK....

### ISSUE THREAD

**Issue by tmg-cr** [twilio/twilio-cli#145]
#### Issue Summary

Validation is failing on Trunk_SID's beginning in TK.

#### Steps to Reproduce

1. Have Trunk_SID beginning in TK
2. Try twilio-cli operations using Trunk_SID as parameter

#### Technical details:

user@cpu:~$ twilio version
twilio-cli/1.9.1 linux-x64 node-v12.14.0

user@cpu:~$ twilio api:trunking:v1:trunks:fetch --sid=TKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -l debug
[DEBUG] Config File: /home/chris/.twilio-cli/config.json
[DEBUG] Using profile: ${TWILIO_API_KEY}/${TWILIO_API_SECRET}
[DEBUG] Schema for "sid": {"maxLength":34,"minLength":34,"pattern":"^TR[0-9a-fA-F]{32}$","type":"string"}
[DEBUG] Provided flags: {"sid":"TKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","cli-log-level":"debug","properties":"sid,friendlyName,domainName","skip-parameter-validation":false,"cli-output-format":"columns"}
 » Flag value validation errors:
 »   sid: "TKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" does not match pattern "^TR[0-9a-fA-F]{32}$"
 » Cannot execute command
[DEBUG] TwilioCliError: Cannot execute command
    at ApiCommandRunner.validateFlags (/home/chris/.nvm/versions/node/v12.14.0/lib/node_modules/twilio-cli/src/services/twilio-api/api-command-runner.js:56:13)
    at ApiCommandRunner.run (/home/chris/.nvm/versions/node/v12.14.0/lib/node_modules/twilio-cli/src/services/twilio-api/api-command-runner.js:21:10)
    at NewCommandClass.run (/home/chris/.nvm/versions/node/v12.14.0/lib/node_modules/twilio-cli/src/base-commands/twilio-api-command.js:36:35)
    at async NewCommandClass._run (/home/chris/.nvm/versions/node/v12.14.0/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (/home/chris/.nvm/versions/node/v12.14.0/lib/node_modules/twilio-cli/node_modules/@oclif/config/lib/config.js:151:9)
    at async Main.run (/home/chris/.nvm/versions/node/v12.14.0/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (/home/chris/.nvm/versions/node/v12.14.0/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/command.js:44:20)

**Comment by childish-sambino** [comment]
Thanks for reporting this. It's a known issue that we're trying to correct in the API spec. In the interim, you can add this flag to the command to skip the check: `--skip-parameter-validation`

**Comment by tmg-cr** [comment]
Ok thank you.

**Comment by childish-sambino** [comment]
Closing as this is not something that can be fixed in the cli itself. I'll circle back if/when the upstream definition is corrected.
