### ISSUE TITLE
When trying to login get error 'uv_os_get_passwd returned ENOENT '

### ISSUE THREAD

**Issue by bhatnagarm** [twilio/twilio-cli#154]
### Issue Summary
When I try to login using Twilio login feature it fails to login giving following error

```
[DEBUG] A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
[DEBUG] SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at Object.userInfo (os.js:265:11)
    at Login.getApiKeyFriendlyName (/usr/local/Cellar/twilio/1.9.6/libexec/src/commands/profiles/create.js:176:47)
    at Login.saveCredentials (/usr/local/Cellar/twilio/1.9.6/libexec/src/commands/profiles/create.js:181:37)
    at Login.run (/usr/local/Cellar/twilio/1.9.6/libexec/src/commands/profiles/create.js:46:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Login._run (/usr/local/Cellar/twilio/1.9.6/libexec/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (/usr/local/Cellar/twilio/1.9.6/libexec/node_modules/@oclif/config/lib/config.js:160:9)
    at async Main.run (/usr/local/Cellar/twilio/1.9.6/libexec/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (/usr/local/Cellar/twilio/1.9.6/libexec/node_modules/@oclif/command/lib/command.js:44:20)
```

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
`twilio login -l debug`

### Exception/Log
``` 
[DEBUG] A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
[DEBUG] SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at Object.userInfo (os.js:265:11)
    at Login.getApiKeyFriendlyName (/usr/local/Cellar/twilio/1.9.6/libexec/src/commands/profiles/create.js:176:47)
    at Login.saveCredentials (/usr/local/Cellar/twilio/1.9.6/libexec/src/commands/profiles/create.js:181:37)
    at Login.run (/usr/local/Cellar/twilio/1.9.6/libexec/src/commands/profiles/create.js:46:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Login._run (/usr/local/Cellar/twilio/1.9.6/libexec/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (/usr/local/Cellar/twilio/1.9.6/libexec/node_modules/@oclif/config/lib/config.js:160:9)
    at async Main.run (/usr/local/Cellar/twilio/1.9.6/libexec/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (/usr/local/Cellar/twilio/1.9.6/libexec/node_modules/@oclif/command/lib/command.js:44:20)
```

### Technical details:
* twilio-cli version: twilio-cli/1.9.6 darwin-x64 node-v13.8.0
* node version: v13.8.0
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
`twilio login -l debug`

# paste output here
```
? Shorthand identifier for your profile: xxxxxxx
You can find your Account SID and Auth Token at https://www.twilio.com/console
 » Your Auth Token will be used once to create an API Key for future CLI access to your Twilio Project, and then forgotten.
? The Account SID for your Twilio Project: ACxxxxxxxxxx
? Your Twilio Auth Token for your Twilio Project: [hidden]
```

**Comment by childish-sambino** [comment]
@bhatnagarm You wouldn't be running this in a Docker container by chance would you?

**Comment by childish-sambino** [comment]
Actually doesn't matter whether or not it's in Docker. This can happen if a user has no `username` or `homedir` ([source](https://nodejs.org/api/os.html#os_os_userinfo_options)).

PR submitted handle this.
