### ISSUE TITLE
Error when generating passcode

### ISSUE THREAD

**Issue by ndahlquist** [twilio/twilio-cli#160]
### Issue Summary
I am attempting to generate a passcode as described here: https://github.com/twilio/twilio-video-app-android#deploy-twilio-access-token-server

### Steps to Reproduce
1. Run `twilio rtc:apps:video:deploy --authentication passcode -l debug`

### Exception/Log
```
nicolas.dahlquist@mp-nicolasd-ml ~/w/twilio-video-app-react> twilio rtc:apps:video:deploy --authentication passcode -l debug
[DEBUG] Config File: /Users/nicolas.dahlquist/.twilio-cli/config.json
[DEBUG] Using profile: testaccount
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services
[DEBUG] User-Agent: @twilio/cli-core/4.5.0 (twilio-node/3.41.1, node.js v13.11.0, darwin 18.7.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Thu, 19 Mar 2020 04:41:33 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"1067","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQef3f3b82ff6d4f649c2934dca6d2d093","twilio-request-duration":"0.020","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services/ZSd53e3a289ad47670c6ac2159386227ff/Environments
[DEBUG] User-Agent: @twilio/cli-core/4.5.0 (twilio-node/3.41.1, node.js v13.11.0, darwin 18.7.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Thu, 19 Mar 2020 04:41:33 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"380","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQaba4f24e6cdc48c18fe38f89f33e7470","twilio-request-duration":"0.025","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] Cannot read property 'sid' of undefined
[DEBUG] TypeError: Cannot read property 'sid' of undefined
    at DeployCommand.getAppInfo (/Users/nicolas.dahlquist/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/helpers.js:74:64)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DeployCommand.run (/Users/nicolas.dahlquist/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/commands/rtc/apps/video/deploy.js:18:21)
    at async DeployCommand._run (/Users/nicolas.dahlquist/.twilio-cli/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (/usr/local/Cellar/twilio/1.11.0/libexec/node_modules/@oclif/config/lib/config.js:160:9)
    at async Main.run (/usr/local/Cellar/twilio/1.11.0/libexec/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (/usr/local/Cellar/twilio/1.11.0/libexec/node_modules/@oclif/command/lib/command.js:44:20)
```

### Technical details:
* twilio-cli version: twilio-cli/1.11.0
* node version: node-v13.11.0
* plugin-rtc: v0.1.2
* darwin-x64

**Comment by childish-sambino** [comment]
@ndahlquist Can you move the issue to here?

https://github.com/twilio-labs/plugin-rtc/issues
