### ISSUE TITLE
Error using twilio-cli to get the access token for the Video app

### ISSUE THREAD

**Issue by sandeep131** [twilio/twilio-cli#162]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.
logged in a sandeep131@gmail.com account

### Steps to Reproduce
1. Ran: twilio plugins:install @twilio-labs/plugin-rtc
2. Run twilio rtc:apps:video:deploy --authentication passcode -l debug

### Code Snippet
```node
# paste code here
```

### Exception/Log
```
# twilio rtc:apps:video:deploy --authentication passcode -l debug
[DEBUG] Config File: /Users/sandeep/.twilio-cli/config.json
[DEBUG] Using profile: BuzzVideo
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services
[DEBUG] User-Agent: @twilio/cli-core/4.5.0 (twilio-node/3.41.1, node.js v8.9.0, darwin 18.7.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Sun, 22 Mar 2020 13:04:03 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"1067","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ8d6ff73aa24a47e4b1d565872a4a65bc","twilio-request-duration":"0.025","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services/ZS5e20b55b32447b80f331ca528d03ff04/Environments
[DEBUG] User-Agent: @twilio/cli-core/4.5.0 (twilio-node/3.41.1, node.js v8.9.0, darwin 18.7.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Sun, 22 Mar 2020 13:04:03 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"380","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ6c394ef89af440d586781014a1da2204","twilio-request-duration":"0.023","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] Cannot read property 'sid' of undefined
[DEBUG] TypeError: Cannot read property 'sid' of undefined
    at DeployCommand.getAppInfo (/Users/sandeep/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/helpers.js:74:64)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Technical details:
* twilio-cli version:
* node version:
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
# paste output here
```

**Comment by childish-sambino** [comment]
Duplicates https://github.com/twilio-labs/plugin-rtc/issues/16
