### ISSUE TITLE
Cannot read property 'sid' of undefined

### ISSUE THREAD

**Issue by agcty** [twilio/twilio-cli#163]
### Issue Summary
Cannot deploy programmable video. Error: `Cannot read property 'sid' of undefined`
I'm trying to run the [twilio-video-app-react](https://github.com/twilio/twilio-video-app-react) but it just won't let me deploy it. I've correctly set up the twilio-cli and added the correct credentials. Not sure if this is the right repo for this issue but the log explicitly tells me to `copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues`

### Steps to Reproduce
```
git clone https://github.com/twilio/twilio-video-app-react.git
cd twilio-video-app-react
npm install -g twilio-cli
twilio login
twilio plugins:install @twilio-labs/plugin-rtc
npm run deploy:twilio-cli
```

### Exception/Log
```
[DEBUG] Config File: /Users/agcty/.twilio-cli/config.json
[DEBUG] Using profile: shopassistant
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services
[DEBUG] User-Agent: @twilio/cli-core/4.5.0 (twilio-node/3.41.1, node.js v13.11.0, darwin 19.3.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Fri, 27 Mar 2020 17:23:15 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"1067","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ502b86aaf3af4b46820ebfddeac9a188","twilio-request-duration":"0.049","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services/ZS80c975abdb94b0a143cec0b06a598ecf/Environments
[DEBUG] User-Agent: @twilio/cli-core/4.5.0 (twilio-node/3.41.1, node.js v13.11.0, darwin 19.3.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Fri, 27 Mar 2020 17:23:15 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"380","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ0aed930783ee4caaa44fe4f1b9d8f3d8","twilio-request-duration":"0.021","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] Cannot read property 'sid' of undefined
[DEBUG] TypeError: Cannot read property 'sid' of undefined
    at DeployCommand.getAppInfo (/Users/agcty/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/helpers.js:76:64)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DeployCommand.run (/Users/agcty/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/commands/rtc/apps/video/deploy.js:18:20)
    at async DeployCommand._run (/Users/agcty/.twilio-cli/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (/usr/local/lib/node_modules/twilio-cli/node_modules/@oclif/config/lib/config.js:160:9)
    at async Main.run (/usr/local/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (/usr/local/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/command.js:44:20)
```

### Technical details:
* twilio-cli version: twilio-cli/1.11.0 darwin-x64 node-v13.11.0
* node version: v13.11.0
* npm version: 6.14.4
```

**Comment by childish-sambino** [comment]
Duplicates https://github.com/twilio-labs/plugin-rtc/issues/16
