### ISSUE TITLE
Twilio CLI error after rerun "Twilio phone-numbers:update" on Macos

### ISSUE THREAD

**Issue by FreakDroid** [twilio/twilio-cli#165]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

### Steps to Reproduce
I was following the tutorial Twilio for [NodeJS](https://www.twilio.com/docs/sms/quickstart/node#sign-up-for-twilio-and-get-a-twilio-phone-number).

I run the project and after that I worte in the terminal `twilio phone-numbers:update "+17048692621" --sms-url="http://localhost:3000/sms" -l debug`. The command works perfect but I saw that I made a mistake in the port of the `sms-url` the port was 1337 so I fixed and rerun the command `twilio phone-numbers:update "+17048692621" --sms-url="http://localhost:1337/sms" -l debug`

And I got the error.
`

### Code Snippet
```var express = require('express');
var router = express.Router();
const MessagingResponse = require('twilio').twiml.MessagingResponse;

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Express' });
});

router.post('/sms', (req, res) => {
  console.log('arrive');
  const twiml = new MessagingResponse();

  twiml.message('The Robots are coming! Head for the hills!');

  res.writeHead(200, {'Content-Type': 'text/xml'});
  res.end(twiml.toString());
});

module.exports = router;
```

### Exception/Log
```
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn ./ngrok ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ./ngrok',
  path: './ngrok',
  spawnargs: [ 'start', '--none', '--log=stdout' ]
}
```

### Technical details:
* MacOs: Mojave
* twilio-cli version: 1.12.0 
* node version: v12.13.0
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
a483e79ff8f8:untitled wilfrelo$ twilio phone-numbers:update "+17048692621" --sms-url="http://localhost:1337/sms" -l debug
[DEBUG] Config File: /Users/wilfrelo/.twilio-cli/config.json
[DEBUG] Using profile: Hackatoon
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://api.twilio.com/2010-04-01/Accounts/AC7e5956a37537947f10ce99bb22e77e8b/IncomingPhoneNumbers.json
[DEBUG] Querystring:
[DEBUG] {"PhoneNumber":"+17048692621"}
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.42.0, node.js v12.13.0, darwin 18.7.0 x64, phone-numbers:update)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Sat, 04 Apr 2020 23:31:40 GMT","content-type":"application/json; charset=utf-8","content-length":"1597","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ1a6e3ec33b6e44fdb98019277ce219ed","twilio-request-duration":"0.120","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"api.twilio.com","strict-transport-security":"max-age=31536000"}
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn ./ngrok ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ./ngrok',
  path: './ngrok',
  spawnargs: [ 'start', '--none', '--log=stdout' ]
}
```

**Comment by FreakDroid** [comment]
I'm going to close this ticket. The laptop that I'm using has blocked many things to run ngrok, I tested the code in other laptop and it's working good.

**Comment by Ghander** [comment]
I see this ngrok error using the C# tutorial at the using the same command as above.

**Comment by shrutiburman** [comment]
Hey @Ghander , DO you want to open a new issue with minimal steps to reproduce the error you're seeing ?

**Comment by Ghander** [comment]
I have already opened a ticket with twilio, thanks.
