### ISSUE TITLE
twilio phone-numbers:update (Numbers) --voice-url  https://1979cca8.ngrok.io -l debug

### ISSUE THREAD

**Issue by rohitjpsingh** [twilio/twilio-cli#166]
### Code Snippet
http://prntscr.com/rujq7q

# Code here
twilio phone-numbers:update +12055832916 --voice-url  https://1979cca8.ngrok.io

# Exception/log here
[DEBUG] Config File: C:\Users\Rohit\.twilio-cli\config.json
[DEBUG] Using profile: ${TWILIO_ACCOUNT_SID}/${TWILIO_AUTH_TOKEN}
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] accountSid must start with AC
[DEBUG] Error: accountSid must start with AC
    at new Twilio (C:\Users\Rohit\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\twilio\lib\rest\Twilio.js:135:11)
    at new initializer (C:\Users\Rohit\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\twilio\lib\index.js:9:10)
    at NumberUpdate.buildClient (C:\Users\Rohit\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@twilio\cli-core\src\base-commands\twilio-client-command.js:112:12)
    at NumberUpdate.get twilioClient [as twilioClient] (C:\Users\Rohit\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@twilio\cli-core\src\base-commands\twilio-client-command.js:99:26)
    at NumberUpdate.run (C:\Users\Rohit\AppData\Roaming\npm\node_modules\twilio-cli\src\commands\phone-numbers\update.js:17:55)
    at async NumberUpdate._run (C:\Users\Rohit\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@oclif\command\lib\command.js:44:20)
    at async Config.runCommand (C:\Users\Rohit\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@oclif\config\lib\config.js:160:9)
    at async Main.run (C:\Users\Rohit\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@oclif\command\lib\main.js:21:9)
    at async Main._run (C:\Users\Rohit\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@oclif\command\lib\command.js:44:20)

### Technical details:
* twilio-cli version:twilio-cli/1.12.0 win32-x64 node-v12.16.1
* node version:v12.16.1

**Comment by childish-sambino** [comment]
Looks like you're storing the account SID and auth token in env vars, and the account SID does start with `AC`.  On windows, trying running `echo %TWILIO_ACCOUNT_SID%` to verify it's correct.

**Comment by rohitjpsingh** [comment]
Yes, I run the following command but the same issue. please help me to solve the issue.
this is code screenshot, please review it.
https://prnt.sc/rx9htg
Console Screenshot:
https://prnt.sc/rx9hfw

Thanks for the reply.

**Comment by childish-sambino** [comment]
Looks like the env var has quotes before and after. Try setting your account SID without quotes. E.g., `setx TWILIO_ACCOUNT_SID=AC...`. Same for the auth token.
