### ISSUE TITLE
npm deployment fails (npm run deploy:twilio-cli) with errno 1

### ISSUE THREAD

**Issue by michael-hintmd** [twilio/twilio-cli#174]
### Issue Summary
I'm just trying to follow your "Deploy your own video collaboration app in five minutes or less" instructions for the ReactJs web app, and it fails when I run `npm run deploy:twilio-cli` 

### Steps to Reproduce
1. `git clone https://github.com/twilio/twilio-video-app-react`
2. `cd twilio-video-app-react`
3. `npm install`
4. `npm install twilio-cli -g`
5. `twilio login`
6. `twilio plugins:install @twilio-labs/plugin-rtc`
7. `npm run deploy:twilio-cli`

### Exception/Log
```» twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the twilio-video-app-react@0.1.0 deploy:twilio-cli script.
```

### Technical details:
* twilio-cli version: 2.0.0 
* macOS: darwin-x64
* node version: node-v13.12.0
* Command output with debug logging enabled (adding `-l debug` to the end of the command didn't work -- failed with "Error: Unexpected argument: debug," so I'm pasting in the npm debug log):
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/13.12.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy:twilio-cli',
1 verbose cli   '--',
1 verbose cli   '--override'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.12.0
4 verbose run-script [
4 verbose run-script   'predeploy:twilio-cli',
4 verbose run-script   'deploy:twilio-cli',
4 verbose run-script   'postdeploy:twilio-cli'
4 verbose run-script ]
5 info lifecycle twilio-video-app-react@0.1.0~predeploy:twilio-cli: twilio-video-app-react@0.1.0
6 info lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: twilio-video-app-react@0.1.0
7 verbose lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: unsafe-perm in lifecycle true
8 verbose lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/michael/source/twilio-video-app-react/node_modules/.bin::/usr/local/bin:/usr/local/Cellar/postgresql@9.6/9.6.11/bin:/usr/local/opt/node/bin:/Users/michael/Library/Android/sdk/platform-tools:/Users/michael/Library/Android/sdk/::/usr/local/bin:/usr/local/Cellar/postgresql@9.6/9.6.11/bin:/usr/local/opt/node/bin:/Users/michael/Library/Android/sdk/platform-tools:/Users/michael/Library/Android/sdk/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/node:/usr/local/bin/npm:/Applications/Wireshark.app/Contents/MacOS
9 verbose lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: CWD: /Users/michael/source/twilio-video-app-react
10 silly lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build "--override"'
10 silly lifecycle ]
11 silly lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: Returned: code: 1  signal: null
12 info lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: Failed to exec deploy:twilio-cli script
13 verbose stack Error: twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build "--override"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid twilio-video-app-react@0.1.0
15 verbose cwd /Users/michael/source/twilio-video-app-react
16 verbose Darwin 19.4.0
17 verbose argv "/usr/local/Cellar/node/13.12.0/bin/node" "/usr/local/bin/npm" "run" "deploy:twilio-cli" "--" "--override"
18 verbose node v13.12.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build "--override"`
22 error Exit status 1
23 error Failed at the twilio-video-app-react@0.1.0 deploy:twilio-cli script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]```

**Comment by michael-hintmd** [comment]
Duplicates twilio-labs/plugin-rtc#16
