### ISSUE TITLE
Deploy the app to Twilio fails

### ISSUE THREAD

**Issue by wotmed** [twilio/twilio-cli#177]
Hi Guys,

Am trying to install on my local Dev which is macOS 10.13. This command fails:
$ npm run deploy:twilio-cli
Details below...
Kind Regards
Trent

### Issue Summary
The deploy step from the 'how to...' is not working. I had some problems with some file permissions with the 'node_modules' directory but have been able to fix that. Now I've gotten to the end step and it still throws the same error:

» twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
How do I add the "-l debug" flag to the npm command? It throws an error as well.

### Steps to Reproduce
1.  Install Twilio CLI
2. Install the RTC plugin
3. $ npm run deploy:twilio-cli

### Exception/Log
```
# paste exception/log here
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy:twilio-cli'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose run-script [
4 verbose run-script   'predeploy:twilio-cli',
4 verbose run-script   'deploy:twilio-cli',
4 verbose run-script   'postdeploy:twilio-cli'
4 verbose run-script ]
5 info lifecycle twilio-video-app-react@0.1.0~predeploy:twilio-cli: twilio-video-app-react@0.1.0
6 info lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: twilio-video-app-react@0.1.0
7 verbose lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: unsafe-perm in lifecycle true
8 verbose lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: PATH: /usr/local/lib/node_modu$
9 verbose lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: CWD: /Users/trentadamson/Sites$
10 silly lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video$
10 silly lifecycle ]
11 silly lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: Returned: code: 1  signal: null
12 info lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: Failed to exec deploy:twilio-cli$
13 verbose stack Error: twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_A$
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm$
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm$
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid twilio-video-app-react@0.1.0
15 verbose cwd /Users/trentadamson/Sites/twilio-video-app-react
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy:twilio-cli"
18 verbose node v12.16.2
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode np$
22 error Exit status 1
23 error Failed at the twilio-video-app-react@0.1.0 deploy:twilio-cli script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

### Technical details:
* twilio-cli version:
* node version:
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
# paste output here
```

**Comment by childish-sambino** [comment]
@wotmed Could you move the issue [here](https://github.com/twilio-labs/plugin-rtc/issues)? (I would if I could)
