### ISSUE TITLE
Installation Error: EACCES permission denied /usr/lib/node_modules/twilio-cli

### ISSUE THREAD

**Issue by octopyth** [twilio/twilio-cli#179]
### Issue Summary
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules/twilio-cli'

### Steps to Reproduce
1. sudo npm install twilio-cli -g
2. export TWILIO_ACCOUNT_VARIABLES
3. sudo npm install twilio-cli -g

### Code Snippet 1
```node
$ sudo npm install twilio-cli -g
```

### Exception/Log
```
/usr/bin/twilio -> /usr/lib/node_modules/twilio-cli/bin/run

> keytar@5.6.0 install /usr/lib/node_modules/twilio-cli/node_modules/keytar
> prebuild-install || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, mkdir '/usr/lib/node_modules/twilio-cli/node_modules/keytar/build'
gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/home/temp/.cache/node-gyp/10.20.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/twilio-cli/node_modules/keytar/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/twilio-cli/node_modules/keytar/.node-gyp'
gyp ERR! System Linux 5.0.0-1025-azure
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/twilio-cli/node_modules/keytar
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> ngrok@3.2.7 postinstall /usr/lib/node_modules/twilio-cli/node_modules/ngrok
> node ./postinstall.js

ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
ngrok - error storing binary to local file { [Error: EACCES: permission denied, open '/usr/lib/node_modules/twilio-cli/node_modules/ngrok/bin/aHR0cHM6Ly9iaW4uZXF1aW5veC5pby9jLzRWbUR6QTdpYUhiL25ncm9rLXN0YWJsZS1saW51eC1hbWQ2NC56aXA=.zip']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path:
   '/usr/lib/node_modules/twilio-cli/node_modules/ngrok/bin/aHR0cHM6Ly9iaW4uZXF1aW5veC5pby9jLzRWbUR6QTdpYUhiL25ncm9rLXN0YWJsZS1saW51eC1hbWQ2NC56aXA=.zip' }
ngrok - install failed, retrying
ngrok - downloading progress: 3768/13773305ngrok - error storing binary to local file Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at WriteStream.Writable.write (_stream_writable.js:299:11)
    at Transform.ondata (_stream_readable.js:710:20)
    at Transform.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Transform.Readable.push (_stream_readable.js:224:10)
    at Transform.push (_stream_transform.js:151:32)
    at Transform.afterTransform (_stream_transform.js:92:10)
ngrok - install failed, retrying
ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
ngrok - error storing binary to local file { [Error: EACCES: permission denied, open '/usr/lib/node_modules/twilio-cli/node_modules/ngrok/bin/aHR0cHM6Ly9iaW4uZXF1aW5veC5pby9jLzRWbUR6QTdpYUhiL25ncm9rLXN0YWJsZS1saW51eC1hbWQ2NC56aXA=.zip']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path:
   '/usr/lib/node_modules/twilio-cli/node_modules/ngrok/bin/aHR0cHM6Ly9iaW4uZXF1aW5veC5pby9jLzRWbUR6QTdpYUhiL25ncm9rLXN0YWJsZS1saW51eC1hbWQ2NC56aXA=.zip' }
ngrok - install failed { [Error: EACCES: permission denied, open '/usr/lib/node_modules/twilio-cli/node_modules/ngrok/bin/aHR0cHM6Ly9iaW4uZXF1aW5veC5pby9jLzRWbUR6QTdpYUhiL25ncm9rLXN0YWJsZS1saW51eC1hbWQ2NC56aXA=.zip']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path:
   '/usr/lib/node_modules/twilio-cli/node_modules/ngrok/bin/aHR0cHM6Ly9iaW4uZXF1aW5veC5pby9jLzRWbUR6QTdpYUhiL25ncm9rLXN0YWJsZS1saW51eC1hbWQ2NC56aXA=.zip' }
```

### Code Snippet 2
```node
$ twilio login
```

### Exception/Log
```
 » Installing keytar ...
error An unexpected error occurred: "EACCES: permission denied, unlink '/home/temp/.twilio-cli/runtime_modules/twilio-cli/node_modules/.bin/detect-libc'".
 » Secure credential storage failed to load.

Alternatively, twilio-cli can use credentials stored in environment variables:

# OPTION 1 (recommended)
TWILIO_ACCOUNT_SID = your Account SID from twil.io/console
TWILIO_API_KEY = an API Key created at twil.io/get-api-key
TWILIO_API_SECRET = the secret for the API Key

# OPTION 2
TWILIO_ACCOUNT_SID = your Account SID from twil.io/console
TWILIO_AUTH_TOKEN = your Auth Token from twil.io/console

Once these environment variables are set, a twilio-cli profile is not required to move forward with installation.
```

### Technical details:
twilio-cli/2.0.1 linux-x64 node-v10.20.1

**Comment by childish-sambino** [comment]
Looks like some optional dependencies could not be installed. Generally speaking, if you can avoid using `sudo` with `npm` then avoid it. Either way, does look like the CLI was installed. You'll just need to use env vars for auth as explained in the log.

**Comment by octopyth** [comment]
hey @childish-sambino, as mentioned in the Steps to Reproduce:
1) sudo npm install twilio-cli -g
2) export TWILIO_ACCOUNT_VARIABLES
3) sudo npm install twilio-cli -g
what you suggest, I've already tried and it didn't work for me.

**Comment by childish-sambino** [comment]
Exporting the env vars is not required in order to install twilio-cli. They are used in lieu of a profile. If the env vars are properly set up, you should be able to run an API command. E.g.,
```
twilio api:core:messages:list
```

**Comment by octopyth** [comment]
Seems to be working fine. Thanks!
```bash
$twilio api:core:messages:list
```
``No results``
