### ISSUE TITLE
Unable to retrieve an authentication passcode

### ISSUE THREAD

**Issue by alexeybk** [twilio/twilio-cli#181]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

### Steps to Reproduce
1. Run server less token generation as described in https://github.com/twilio/twilio-video-app-ios
2. Command `twilio rtc:apps:video:deploy --authentication passcode` fails

### Code Snippet
```node
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-cli version: twilio-cli/2.0.2 
* node version: node-v14.2.0 , tried to downgrade to node@10 (older versions aren't supported by Homebrew now) with no relief
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
Alexeys-MBP:~ alexeybk$ twilio rtc:apps:video:deploy --authentication passcode -l debug
[DEBUG] Config File: /Users/alexeybk/.twilio-cli/config.json
[DEBUG] Using profile: aak016
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.43.1, node.js v14.2.0, darwin 19.3.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Thu, 14 May 2020 09:10:42 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"1067","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ43098674e2274cd385f4ac119ac35191","twilio-request-duration":"0.039","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services/ZSefe14f62a9490f4c364fd946ce3287c8/Environments
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.43.1, node.js v14.2.0, darwin 19.3.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Thu, 14 May 2020 09:10:42 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"380","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ046752eb0c3740cbb188160b6c3e1b03","twilio-request-duration":"0.031","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] Cannot read property 'sid' of undefined
[DEBUG] TypeError: Cannot read property 'sid' of undefined
    at DeployCommand.getAppInfo (/Users/alexeybk/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/helpers.js:77:64)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DeployCommand.run (/Users/alexeybk/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/commands/rtc/apps/video/deploy.js:18:20)
    at async DeployCommand._run (/Users/alexeybk/.twilio-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/lib/node_modules/twilio-cli/node_modules/@oclif/config/lib/config.js:172:9)
    at async Main.run (/usr/local/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/main.js:22:9)
    at async Main._run (/usr/local/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/command.js:43:20)
```

**Comment by alexeybk** [comment]
Sorry, didn't mention the troubleshooting section there. It helped. Closing the request.
