### ISSUE TITLE
Unexpected token error when invoking login

### ISSUE THREAD

**Issue by gleuch** [twilio/twilio-cli#182]
### Issue Summary

Upon install (homebrew, npm, etc), receive `Unexpected token` after invoking `twilio login`

#### Via homebrew
1. `brew tap twilio/brew && brew install twilio`
2. `twilio login`
3. Error thrown
```
/Users/developer/.nvm/versions/node/v8.11.3/lib/node_modules/twilio-cli/node_modules/@twilio/cli-core/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/developer/.nvm/versions/node/v8.11.3/lib/node_modules/twilio-cli/node_modules/@twilio/cli-core/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
```

#### Via Node v8.11.3 with NPM v5.6.0
1. `npm install -g twilio-cli`
2. `twilio login`
3. Error thrown
```
/Users/developer/.nvm/versions/node/v8.11.3/lib/node_modules/twilio-cli/node_modules/@twilio/cli-core/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/developer/.nvm/versions/node/v8.11.3/lib/node_modules/twilio-cli/node_modules/@twilio/cli-core/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
```

### Code Snippet

_N/A_

### Exception/Log

_See above_

### Technical details:
* twilio-cli version: **2.0.2**
* node version: **8.13.6**
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
**Unable to generate, throws error log above**
* OS: **Mac 10.14.6 (Mojave)**

### Additional Notes:

This is a reported issue with `fs-extras` package. https://github.com/jprichardson/node-fs-extra/issues/771

I am able to get this to work using NVM with Node v12.16.2 (NPM v6.14.4).

**Comment by childish-sambino** [comment]
Support for Node8 with twilio-cli was dropped with the v2 release since Node8 is EOL. Recommend upgrading to at least Node10.
