### ISSUE TITLE
Cannot `npm run deploy:twilio-cli` on Mac

### ISSUE THREAD

**Issue by hr-danielavram** [twilio/twilio-cli#183]
### Issue Summary
I was following the steps from https://www.twilio.com/blog/open-source-video-apps-reactjs-ios-android but at Deploy phase I get an error and cannot deploy.

### Steps to Reproduce
These are the ones I followed from the tutorial above.
1. git clone https://github.com/twilio/twilio-video-app-react - ✅
2. cd twilio-video-app-react - ✅
3. npm install - ✅
4. npm install twilio-cli -g - ✅
5. twilio login - ✅
6. twilio plugins:install @twilio-labs/plugin-rtc - ✅
7. npm run deploy:twilio-cli - 🚫

### Technical details:
* twilio-cli version: twilio-cli/2.0.2 darwin-x64 node-v13.8.0
* node version: v13.8.0
* npm version: 6.14.5
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
npm run deploy:twilio-cli -- --override -l debug

> twilio-video-app-react@0.1.0 deploy:twilio-cli /Users/daniel.avram/Projects/hillrom/twilio/twilio-video-app-react
> cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build "--override" "-l" "debug"


> twilio-video-app-react@0.1.0 build /Users/daniel.avram/Projects/hillrom/twilio/twilio-video-app-react
> node ./scripts/build.js

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  264.74 KB  build/static/js/2.c4369f5a.chunk.js
  14.25 KB   build/static/js/main.cd7f0f6e.chunk.js
  784 B      build/static/js/runtime-main.fa60846a.js

[DEBUG] Config File: /Users/daniel.avram/.twilio-cli/config.json
[DEBUG] Using profile: test_profile_1
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.43.1, node.js v13.8.0, darwin 19.4.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Wed, 20 May 2020 06:49:43 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"1067","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ302b02f9a6e84168a9f6223bad7f0a90","twilio-request-duration":"0.021","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services/ZS06606eefc412f08d420a935c16855a10/Environments
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.43.1, node.js v13.8.0, darwin 19.4.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Wed, 20 May 2020 06:49:43 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"380","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQd08f26910ff642818bc12879958ec249","twilio-request-duration":"0.023","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] Cannot read property 'sid' of undefined
[DEBUG] TypeError: Cannot read property 'sid' of undefined
    at DeployCommand.getAppInfo (/Users/daniel.avram/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/helpers.js:77:64)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DeployCommand.run (/Users/daniel.avram/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/commands/rtc/apps/video/deploy.js:18:20)
    at async DeployCommand._run (/Users/daniel.avram/.twilio-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/lib/node_modules/twilio-cli/node_modules/@oclif/config/lib/config.js:172:9)
    at async Main.run (/usr/local/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/main.js:22:9)
    at async Main._run (/usr/local/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/command.js:43:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build "--override" "-l" "debug"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the twilio-video-app-react@0.1.0 deploy:twilio-cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/daniel.avram/.npm/_logs/2020-05-20T06_49_44_035Z-debug.log
```

**Comment by hr-danielavram** [comment]
Fixed by running:
1. Run twilio plugins:update to update the rtc plugin to the latest version.
2. Run twilio rtc:apps:video:delete to delete any existing authentication servers.
3. Run twilio rtc:apps:video:deploy --authentication passcode to deploy a new authentication server.

**Comment by adityasudhakar** [comment]
@hr-danielavram , how did ^ fix? I'm stuck at the same place you were!
