### ISSUE TITLE
Plugins is not a constructor in 2.1.0

### ISSUE THREAD

**Issue by johnmmason** [twilio/twilio-cli#187]
### Issue Summary
This issue is a reoccurrence of issue #185 which occurred on `2.0.2` and was fixed in `2.0.3`.  I am experiencing the previously resolved issue on `2.1.0`.

### Steps to Reproduce
The issue occurred while running the command:

```
twilio phone-numbers:update "+15127175950" --sms-url="http://localhost:5000/sms" -l debug
```

### Code Snippet
```
[DEBUG] Found ngrok version in "twilio-cli" optionalDependencies: ^3.2.7
 » Installing ngrok ...
[DEBUG] Found command "phone-numbers:update" plugin: twilio-cli
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio/twilio-cli/issues"
[DEBUG] Plugins is not a constructor
[DEBUG] TypeError: Plugins is not a constructor
    at requireInstall (/usr/local/Cellar/twilio/2.1.0/libexec/node_modules/@twilio/cli-core/src/services/require-install.js:104:19)
    at NumberUpdate.install (/usr/local/Cellar/twilio/2.1.0/libexec/node_modules/@twilio/cli-core/src/base-commands/base-command.js:153:12)
    at NumberUpdate.run (/usr/local/Cellar/twilio/2.1.0/libexec/src/commands/phone-numbers/update.js:37:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async NumberUpdate._run (/usr/local/Cellar/twilio/2.1.0/libexec/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/Cellar/twilio/2.1.0/libexec/node_modules/@oclif/config/lib/config.js:172:9)
    at async Main.run (/usr/local/Cellar/twilio/2.1.0/libexec/node_modules/@oclif/command/lib/main.js:22:9)
    at async Main._run (/usr/local/Cellar/twilio/2.1.0/libexec/node_modules/@oclif/command/lib/command.js:43:20)
```

### Technical details:
* twilio-cli version:
```
% twilio --version
twilio-cli/2.1.0 darwin-x64 node-v14.3.0
```

**Comment by childish-sambino** [comment]
Able to recreate this locally. Looks like the previous fix is no longer valid due to transitive dependency issues. Checking for what the proper fix should be ...
