### ISSUE TITLE
Cannot read property 'sid' of undefined

### ISSUE THREAD

**Issue by DhiruVDB** [twilio/twilio-cli#188]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.
- getting issue while running command **twilio rtc:apps:video:deploy --authentication passcode -l debug**

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```node
# paste code here
```

### Exception/Log
```
~ twilio rtc:apps:video:deploy --authentication passcode -l debug
[DEBUG] Config File: /Users/dhirendra/.twilio-cli/config.json
[DEBUG] Using profile: ${TWILIO_ACCOUNT_SID}/${TWILIO_AUTH_TOKEN}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.44.0, node.js v14.3.0, darwin 19.4.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Fri, 29 May 2020 07:01:58 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"1067","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQec0837fe4ca7466681589d7a8c91928e","twilio-request-duration":"0.032","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services/ZSa2f64c60ca57f5e07b7c03f8ac13d076/Environments
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.44.0, node.js v14.3.0, darwin 19.4.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Fri, 29 May 2020 07:01:59 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"380","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ6c8bd123c22d4863820d95811c4d7c0e","twilio-request-duration":"0.035","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] Cannot read property 'sid' of undefined
[DEBUG] TypeError: Cannot read property 'sid' of undefined
    at DeployCommand.getAppInfo (/Users/dhirendra/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/helpers.js:77:64)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DeployCommand.run (/Users/dhirendra/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/commands/rtc/apps/video/deploy.js:18:20)
    at async DeployCommand._run (/Users/dhirendra/.twilio-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/lib/node_modules/twilio-cli/node_modules/@oclif/config/lib/config.js:172:9)
    at async Main.run (/usr/local/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/main.js:22:9)
    at async Main._run (/usr/local/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/command.js:43:20)
➜  ~
# paste exception/log here
```

### Technical details:
* twilio-cli version:

* node version:
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
# paste output here
```

**Comment by childish-sambino** [comment]
Do you mind re-opening the issue here? https://github.com/twilio-labs/plugin-rtc/issues

I don't have transfer power. _Note that we're working on a fix to direct plugin issues to use the plugin URL when reporting issues._
