### ISSUE TITLE
Trouble logging in

### ISSUE THREAD

**Issue by Bharathsrinivasan** [twilio/twilio-cli#196]
### Issue Summary
getting error while trying to login my machine using twilio-cli
```
? The Account SID for your Twilio Account or Subaccount: AC8429ac9937106855ba17053ac8579588
? Your Twilio Auth Token for your Twilio Account or Subaccount: [hidden]
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://api.twilio.com/2010-04-01/Accounts/AC8429ac9937106855ba17053ac8579588.json
[DEBUG] User-Agent: @twilio/cli-core/5.6.0 (twilio-node/3.47.0, node.js v10.0.0, darwin 19.5.0 x64, login)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Thu, 02 Jul 2020 06:35:11 GMT","content-type":"application/json; charset=utf-8","content-length":"2261","connection":"close","last-modified":"Tue, 23 Jun 2020 12:42:41 +0000","twilio-concurrent-requests":"1","etag":"c86766a803a367c30d68eb028bc250ff","twilio-request-id":"RQ2aa9637799e543e08d07c3da33786ad8","twilio-request-duration":"0.019","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"api.twilio.com","strict-transport-security":"max-age=31536000"}
? Shorthand identifier for your profile: SK2f5feed62a43c622cff4a78b9a84ccde
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] POST https://api.twilio.com/2010-04-01/Accounts/AC8429ac9937106855ba17053ac8579588/Keys.json
[DEBUG] Form data:
[DEBUG] FriendlyName=twilio-cli%20for%20srinivasan-0963%20on%20srinivasan-0963
[DEBUG] User-Agent: @twilio/cli-core/5.6.0 (twilio-node/3.47.0, node.js v10.0.0, darwin 19.5.0 x64, login)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 201
[DEBUG] response.headers: {"date":"Thu, 02 Jul 2020 06:35:19 GMT","content-type":"application/json; charset=utf-8","content-length":"263","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ5b6acba14d0640ca916d0a50f229ef59","twilio-request-duration":"0.036","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"api.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] {"sid":"SK64fde80dd19e274ebfddbded6dbc93d0","friendlyName":"twilio-cli for srinivasan-0963 on srinivasan-0963","dateCreated":"2020-07-02T06:35:19.000Z","dateUpdated":"2020-07-02T06:35:19.000Z","secret":"XXXXXXXXXXXXXXXXX"}
[DEBUG] Found command "login" plugin: twilio-cli
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio/twilio-cli/issues"
[DEBUG] EEXIST: file already exists, mkdir '/Users/srinivasan-0963/.twilio-cli'
[DEBUG] Error: EEXIST: file already exists, mkdir '/Users/srinivasan-0963/.twilio-cli'
    at Object.fs.mkdirSync (fs.js:840:3)
    at Config.save (/usr/local/lib/node_modules/twilio-cli/node_modules/@twilio/cli-core/src/services/config.js:183:8)
    at Login.saveCredentials (/usr/local/lib/node_modules/twilio-cli/src/commands/profiles/create.js:242:54)
```

**Comment by childish-sambino** [comment]
Minimum Node version required is 10.12.0

I'm working on updating the getting started guide to say this.

**Comment by eshanholtz** [comment]
Hey @Bharathsrinivasan 

It looks like your API key secret was accidentally included in the debug output. I've gone ahead and removed it from your original post, but we strongly urge you to go ahead and rotate that key to ensure security. We're going to update the debug output to hide these secrets in the future, so it doesn't happen again.

Thanks!
