### ISSUE TITLE
Install issues due to Python version

### ISSUE THREAD

**Issue by dprothero** [twilio/twilio-cli#2]
Error details:
```% npm install                                                                                                                                                                                       (10010)

> keytar@4.2.1 install /Users/zhauser/code/twilio-cli/node_modules/keytar
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.9.0 runtime=node arch=x64 platform=darwin)
gyp ERR! configure error
gyp ERR! stack Error: Python executable "/usr/local/opt/python/libexec/bin/python" is v3.6.5, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Users/zhauser/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:501:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/zhauser/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:280:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:599:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/zhauser/.nvm/versions/node/v10.9.0/bin/node" "/Users/zhauser/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/zhauser/code/twilio-cli/node_modules/keytar
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@4.2.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@4.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhauser/.npm/_logs/2018-09-28T16_15_37_944Z-debug.log
```

My system is a Mac. With my `PATH`, `python` refers to python3. The only way I can get python2 at this point is directly running `/usr/bin/python`. Unfortunately I don't recall how I got my system to this state. It might have just been `brew install python` (which is now python3) though.

Possible fixes:
- `npm install --python=/path/to/python2` (tested and works)
- have a `python2` command, e.g. if (in my case) I'd run `ln -s /usr/bin/python /usr/local/bin/python2` (not tested, but I saw some docs about `gyp` now looking for `python2` first)

**Comment by dprothero** [comment]
Possibly the same as #10

**Comment by childish-sambino** [comment]
`keytar` was recently moved to an optional dependency: https://github.com/twilio/twilio-cli-core/pull/62

This should allow for installation on more OS types. If `keytar` is not available, env vars can be used for auth: https://www.twilio.com/docs/twilio-cli/general-usage#want-to-use-environment-variables-instead-of-creating-a-profile
