### ISSUE TITLE
Twilio CLI credential storage fails with Node 14

### ISSUE THREAD

**Issue by tobyallen** [twilio/twilio-cli#203]
### Issue Summary
IF using node 14 then the keytar integration fails when running commands. Mac

### Steps to Reproduce
1. Use Twilio CLI with Node 14
2. Attempt to run a command that uses or access a Twilio profile.
3. If you use NVM and switch to using node 12 all commands execute successfully.

### Exception/Log
```
twilio serverless:init --template:sync-token
(node:9985) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9985) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:9985) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
 » Installing keytar ...
error /Users/tallen/.twilio-cli/runtime_modules/@twilio-labs/plugin-serverless/node_modules/keytar: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /Users/tallen/.twilio-cli/runtime_modules/@twilio-labs/plugin-serverless/node_modules/keytar
Output:
prebuild-install WARN install No prebuilt binaries found (target=14.6.0 runtime=node arch=x64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.6.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp http GET https://nodejs.org/download/release/v14.6.0/node-v14.6.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v14.6.0/node-v14.6.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v14.6.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v14.6.0/SHASUMS256.txt
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/tallen/.nvm/versions/node/v14.6.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tallen/.twilio-cli/runtime_modules/@twilio-labs/plugin-serverless/node_modules/keytar/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tallen/.nvm/versions/node/v14.6.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tallen/Library/Caches/node-gyp/14.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/tallen/Library/Caches/node-gyp/14.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/tallen/.nvm/versions/node/v14.6.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/tallen/Library/Caches/node-gyp/14.6.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/tallen/.twilio-cli/runtime_modules/@twilio-labs/plugin-serverless/node_modules/keytar',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/tallen/.nvm/versions/node/v14.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/tallen/.nvm/versions/node/v14.6.0/bin/node" "/Users/tallen/.nvm/versions/node/v14.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tallen/.twilio-cli/runtime_modules/@twilio-labs/plugin-serverless/node_modules/keytar
gyp ERR! node -v v14.6.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
 » Secure credential storage failed to load.

Alternatively, twilio-cli can use credentials stored in environment variables:

# OPTION 1 (recommended)
TWILIO_ACCOUNT_SID = your Account SID from twil.io/console
TWILIO_API_KEY = an API Key created at twil.io/get-api-key
TWILIO_API_SECRET = the secret for the API Key

# OPTION 2
TWILIO_ACCOUNT_SID = your Account SID from twil.io/console
TWILIO_AUTH_TOKEN = your Auth Token from twil.io/console

Once these environment variables are set, a twilio-cli profile is not required to move forward with installation.
 ›   Error: EEXIT: 1
 ›   Code: EEXIT

```

### Technical details:
* twilio-cli version:
* node version: 14.6.0
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```

```

**Comment by childish-sambino** [comment]
Looks like this is the underlying error: `No Xcode or CLT version detected`

Blog post on how to resolve this: https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d

**Comment by tobyallen** [comment]
Interestingly those steps fixed credential storage but it still spews some errors in Node 14.

Node 14 
```   
➜  hackathon node --version
v14.6.0
➜  hackathon twilio serverless:deploy                        
(node:20608) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20608) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:20608) Warning: Accessing non-existent property 'which' of module exports inside circular dependency

Deploying functions & assets to the Twilio Runtime

```

versus Node 12

```
➜  hackathon nvm use 12
Now using node v12.18.0 (npm v6.14.4)
➜  hackathon node --version
v12.18.0
➜  hackathon twilio serverless:deploy
 » Installing keytar ...

Deploying functions & assets to the Twilio Runtime

```

**Comment by childish-sambino** [comment]
Looks like a dependency issue with the serverless plugin. Best to follow-up here: https://github.com/twilio-labs/plugin-serverless/issues

Feel free to tag me there if necessary.
