### ISSUE TITLE
Error deploying twilio-video-app-react

### ISSUE THREAD

**Issue by timscott** [twilio/twilio-cli#211]
### Issue Summary
Error deploying twilio-video-app-react per https://github.com/twilio/twilio-video-app-react#deploy-the-app-to-twilio

### Steps to Reproduce

Deploy once, then delete, then deploy again.

### Exception/Log

First time after delete:

```
Something went wrong { HTTPError: Response code 409 (CONFLICT)
    at EventEmitter.emitter.on (/Users/tscott/.twilio-cli/node_modules/got/source/as-promise.js:74:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HTTPError',
  host: undefined,
  hostname: 'serverless.twilio.com',
  method: 'POST',
  path:
   '/v1/Services/ZSeeaaec4a523f0a2a0551b34a021f2f6a/Environments',
  socketPath: undefined,
  protocol: 'https:',
  url:
   'https://serverless.twilio.com/v1/Services/ZSeeaaec4a523f0a2a0551b34a021f2f6a/Environments',
  gotOptions:
   { path:
      '/v1/Services/ZSeeaaec4a523f0a2a0551b34a021f2f6a/Environments',
     protocol: 'https:',
     hostname: 'serverless.twilio.com',
     hash: '',
     search: '',
     pathname:
      '/v1/Services/ZSeeaaec4a523f0a2a0551b34a021f2f6a/Environments',
     href:
      'https://serverless.twilio.com/v1/Services/ZSeeaaec4a523f0a2a0551b34a021f2f6a/Environments',
     retry:
      { retries: [Function],
        methods: [Set],
        statusCodes: [Set],
        errorCodes: [Set] },
     headers:
      { 'user-agent': 'twilio-serverless-api',
        accept: 'application/json',
        'accept-encoding': 'gzip, deflate',
        'content-type': 'application/x-www-form-urlencoded',
        'content-length': 105 },
     hooks:
      { beforeError: [],
        init: [],
        beforeRequest: [],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: [] },
     decompress: true,
     throwHttpErrors: true,
     followRedirect: true,
     stream: false,
     form: true,
     json: true,
     cache: false,
     useElectronNet: false,
     baseUrl: [Getter/Setter],
     auth:
      'SK38538a8d3897ef022a440fb1cd0e1937:0LuI1uB7b6w9dNVW39f5kXg8c4lSEdCI',
     body:
      'UniqueName=dev-environment&DomainSuffix=dev&FriendlyName=dev-environment+Environment+%28Created+by+CLI%29',
     method: 'POST' },
  statusCode: 409,
  statusMessage: 'CONFLICT',
  headers:
   { date: 'Wed, 05 Aug 2020 22:35:35 GMT',
     'content-type': 'application/json',
     'content-length': '166',
     connection: 'close',
     'twilio-request-id': 'RQ5094560b562b4e9697798622d7755f6f',
     'twilio-request-duration': '0.036',
     'access-control-allow-origin': '*',
     'access-control-allow-headers':
      'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since',
     'access-control-allow-methods': 'GET, POST, DELETE, OPTIONS',
     'access-control-expose-headers': 'ETag',
     'access-control-allow-credentials': 'true',
     'x-powered-by': 'AT-5000',
     'x-shenanigans': 'none',
     'x-home-region': 'us1',
     'x-api-domain': 'serverless.twilio.com',
     'strict-transport-security': 'max-age=31536000' },
  body:
   { code: 20409,
     message:
      'Environment with this UniqueName or DomainSuffix already exists.',
     more_info: 'https://www.twilio.com/docs/errors/20409',
     status: 409 } }
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
deploying app... !
 ›   Error: EEXIT: 1
 ›   Code: EEXIT
```

Subsequent deploys :

```
[DEBUG] Config File: /Users/tscott/.twilio-cli/config.json
[DEBUG] Using profile: tim
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.48.1, node.js v10.15.3, darwin 17.7.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Wed, 05 Aug 2020 22:26:37 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"1067","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ32d416c8a2f14ea893fd49b38b0c4fc4","twilio-request-duration":"0.037","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services/ZSa18337df4705c30e40a9e7eedb2ef80d/Environments
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.48.1, node.js v10.15.3, darwin 17.7.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Wed, 05 Aug 2020 22:26:37 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"380","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQec35e218704d444f8501a59719914e90","twilio-request-duration":"0.023","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] Cannot read property 'sid' of undefined
[DEBUG] TypeError: Cannot read property 'sid' of undefined
    at DeployCommand.getAppInfo (/Users/tscott/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/helpers.js:77:64)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 ›   Error: EEXIT: 1
 ›   Code: EEXIT
```

**Comment by forestallers** [comment]
Try this, i got fixed by below steps

twilio plugins:update 
twilio rtc:apps:video:delete
npm run deploy:twilio-cli

**Comment by timscott** [comment]
@forestallers - That worked, thanks!

I'm leaving this open in case Twilio wants to update docs or do something to prevent this scenario.

**Comment by eshanholtz** [comment]
The steps were documented here: https://github.com/twilio/twilio-video-app-react#troubleshooting-the-twilio-cli

Closing as no further work needs to be done.
