### ISSUE TITLE
twilio api:video:v1:recording-settings:default:fetch

### ISSUE THREAD

**Issue by hieuvn1301** [twilio/twilio-cli#221]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.

### Code Snippet
```node
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* twilio-cli version: 
* node version:
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
# paste output here
```
I call this command: twilio api:video:v1:recording-settings:default:fetch
and found this error
[DEBUG] Config File: C:\Users\hieuvn\.twilio-cli\config.json
[DEBUG] Using profile: hieuvn
[DEBUG] Provided flags: {"cli-log-level":"debug","properties":"friendlyName,awsStorageEnabled,encryptionEnabled","skip-parameter-validation":false,"cli-output-format":"columns"}
[DEBUG] domainName=video, path=/v1/RecordingSettings/Default, actionName=fetch
[DEBUG] Found command "api:video:v1:recording-settings:default:fetch" plugin: twilio-cli
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio/twilio-cli/issues"
[DEBUG] Cannot read property 'forEach' of undefined
[DEBUG] TypeError: Cannot read property 'forEach' of undefined
    at ApiCommandRunner.execute (C:\Users\hieuvn\AppData\Roaming\npm\node_modules\twilio-cli\src\services\twilio-api\api-command-runner.js:78:18)
    at ApiCommandRunner.run (C:\Users\hieuvn\AppData\Roaming\npm\node_modules\twilio-cli\src\services\twilio-api\api-command-runner.js:26:17)
    at NewCommandClass.run (C:\Users\hieuvn\AppData\Roaming\npm\node_modules\twilio-cli\src\base-commands\twilio-api-command.js:39:35)
    at async NewCommandClass._run (C:\Users\hieuvn\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@oclif\command\lib\command.js:43:20)
    at async Config.runCommand (C:\Users\hieuvn\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@oclif\config\lib\config.js:173:24)
    at async Main.run (C:\Users\hieuvn\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@oclif\command\lib\main.js:27:9)
    at async Main._run (C:\Users\hieuvn\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@oclif\command\lib\command.js:43:20)

**Comment by thinkingserious** [comment]
Thanks for reporting this @hieuvn1301!

I was able to reproduce this on `twilio-cli` v2.10.0.

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer

**Comment by yalla** [comment]
Also happens on `twilio-cli/2.12.0 linux-x64 node-v12.18.2`

**Comment by yalla** [comment]
Function `api:voice:v1:settings:fetch` is also affected.

```
[DEBUG] Cannot read property 'forEach' of undefined
[DEBUG] TypeError: Cannot read property 'forEach' of undefined
    at ApiCommandRunner.execute (/home/alex/.nvm/versions/node/v12.18.2/lib/node_modules/twilio-cli/src/services/twilio-api/api-command-runner.js:78:18)
    at ApiCommandRunner.run (/home/alex/.nvm/versions/node/v12.18.2/lib/node_modules/twilio-cli/src/services/twilio-api/api-command-runner.js:26:17)
    at NewCommandClass.run (/home/alex/.nvm/versions/node/v12.18.2/lib/node_modules/twilio-cli/src/base-commands/twilio-api-command.js:39:35)
    at async NewCommandClass._run (/home/alex/.nvm/versions/node/v12.18.2/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/home/alex/.nvm/versions/node/v12.18.2/lib/node_modules/twilio-cli/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/home/alex/.nvm/versions/node/v12.18.2/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/main.js:27:9)
    at async Main._run (/home/alex/.nvm/versions/node/v12.18.2/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/command.js:43:20)
```
