### ISSUE TITLE
CLI not interacting correctly with https proxy

### ISSUE THREAD

**Issue by gkanz** [twilio/twilio-cli#223]
### Issue Summary
We are using the cli behind a https proxy. The axios http client used by the cli is using the environment variables and sends it's request via the forward proxy (as specified by the `http_proxy` and `https_proxy` environment variables). However, it is not issuing a CONNECT for the https proxy. This results in a failed request.

See https://github.com/axios/axios/issues/2072

### Steps to Reproduce
1. Have a locally running forward proxy
2. Be on a network behind a https authenticating proxy
3. Run any twilio cli command

### Reproduce Behaviour
This will cause a `GET` to be sent to the forward proxy.
```node
const axios = require('axios');
axios.get('https://www.twilio.com')
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  })
  .then(function () {
  });
```

### Example of good behaviour
```
curl https://www.twilio.com
```

### Suggested fix
This will cause a `CONNECT` to be sent to the forward proxy.
```node
const HttpsProxyAgent = require('https-proxy-agent');

const axiosConfig = {
    proxy: false,
    httpsAgent: new HttpsProxyAgent(process.env.http_proxy)
};

const axios = require('axios').create(axiosConfig);
axios.get('https://www.twilio.com')
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  })
  .then(function () {
  });

```
The impacted code is actually in the cli-core repo: https://github.com/twilio/twilio-cli-core/blob/main/src/services/cli-http-client.js.
### Exception/Log
```
See below.
```

### Technical details:
* twilio-cli version: twilio-cli/2.11.0 darwin-x64 node-v10.22.1
* node version:v10.22.1
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
[DEBUG] Config File: /Users/k***/.twilio-cli/config.json
[DEBUG] Using profile: ${TWILIO_API_KEY}/${TWILIO_API_SECRET}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://api.twilio.com/2010-04-01/Accounts/AC***/IncomingPhoneNumbers.json
[DEBUG] Custom HTTP Headers:
[DEBUG] User-Agent: @twilio/cli-core/5.10.0 (twilio-node/3.50.0, node.js v10.22.1, darwin 19.6.0 x64, phone-numbers:list)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"access-control-allow-credentials":"true","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-allow-origin":"*","access-control-expose-headers":"ETag","content-length":"254","content-type":"application/xml; charset=utf-8","date":"Fri, 16 Oct 2020 03:33:26 GMT","strict-transport-security":"max-age=31536000","twilio-request-duration":"0.002","twilio-request-id":"RQ***","x-api-domain":"api.twilio.com","x-home-region":"us1","x-powered-by":"AT-5000","x-shenanigans":"none","connection":"close"}
[DEBUG] Found command "phone-numbers:list" plugin: twilio-cli
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio/twilio-cli/issues"
[DEBUG] Unexpected token < in JSON at position 0
[DEBUG] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingPhoneNumberPage.Page.processResponse (/Users/k***/.nvm/versions/node/v10.22.1/lib/node_modules/twilio-cli/node_modules/twilio/lib/base/Page.js:160:17)
    at IncomingPhoneNumberPage.Page (/Users/k***/.nvm/versions/node/v10.22.1/lib/node_modules/twilio-cli/node_modules/twilio/lib/base/Page.js:16:22)
    at new IncomingPhoneNumberPage (/Users/k***/.nvm/versions/node/v10.22.1/lib/node_modules/twilio-cli/node_modules/twilio/lib/rest/api/v2010/account/incomingPhoneNumber.js:542:30)
    at Function.<anonymous> (/Users/k***/.nvm/versions/node/v10.22.1/lib/node_modules/twilio-cli/node_modules/twilio/lib/rest/api/v2010/account/incomingPhoneNumber.js:284:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by thinkingserious** [comment]
Hello @gkanz,

Thank you for taking to the time to report! 

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer

**Comment by childish-sambino** [comment]
Internal tracking ID: DI-889
