### ISSUE TITLE
Libsecret Package Issue

### ISSUE THREAD

**Issue by Rubix982** [twilio/twilio-cli#233]
### Issue Summary
A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

Following the Twilio docs to setting up a nodejs application, here, https://www.twilio.com/docs/sms/quickstart/node#install-the-twilio-cli, I ran `npm install -g twilio-cli`, and I was then asked to run `twilio login`, which is wehre I was hit this wall of error,

```
» Installing keytar ...
error /home/saif/.twilio-cli/runtime_modules/twilio-cli/node_modules/keytar: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /home/saif/.twilio-cli/runtime_modules/twilio-cli/node_modules/keytar
Output:
prebuild-install WARN install No prebuilt binaries found (target=15.3.0 runtime=node arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.3.0 | linux | x64
gyp info find Python using Python version 3.8.5 found at "/home/saif/anaconda3/bin/python3"
gyp info spawn /home/saif/anaconda3/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/saif/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/saif/.twilio-cli/runtime_modules/twilio-cli/node_modules/keytar/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/saif/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/saif/.cache/node-gyp/15.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/saif/.cache/node-gyp/15.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/saif/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/saif/.cache/node-gyp/15.3.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/saif/.twilio-cli/runtime_modules/twilio-cli/node_modules/keytar',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package libsecret-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsecret-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsecret-1' found
gyp: Call to 'pkg-config --cflags libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/saif/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
gyp ERR! System Linux 5.4.0-53-generic
gyp ERR! command "/home/saif/.nvm/versions/node/v15.3.0/bin/node" "/home/saif/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/saif/.twilio-cli/runtime_modules/twilio-cli/node_modules/keytar
gyp ERR! node -v v15.3.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
 » Secure credential storage failed to load.

Alternatively, twilio-cli can use credentials stored in environment variables:

# OPTION 1 (recommended)
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_API_KEY=an API Key created at twil.io/get-api-key
export TWILIO_API_SECRET=the secret for the API Key

# OPTION 2
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_AUTH_TOKEN=your Auth Token from twil.io/console

Once these environment variables are set, a twilio-cli profile is not required and you may skip the "login" step.
```

So I tried OPTION #2, and exported these variables inside my `~/.zshrc` to no avail. I installed `libsecret-1` by running `sudo apt install libsecret-1-dev`, no difference. 

### Steps to Reproduce
1. Follow this tuts, https://www.twilio.com/docs/sms/quickstart/node#install-the-twilio-cli
2. Run `npm install -g twilio-cli`
3. Run `twilio login`.

### Code Snippet
Not exactly code related.

### Exception/Log
```
# » Installing keytar ...
error /home/saif/.twilio-cli/runtime_modules/twilio-cli/node_modules/keytar: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /home/saif/.twilio-cli/runtime_modules/twilio-cli/node_modules/keytar
Output:
prebuild-install WARN install No prebuilt binaries found (target=15.3.0 runtime=node arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.3.0 | linux | x64
gyp info find Python using Python version 3.8.5 found at "/home/saif/anaconda3/bin/python3"
gyp info spawn /home/saif/anaconda3/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/saif/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/saif/.twilio-cli/runtime_modules/twilio-cli/node_modules/keytar/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/saif/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/saif/.cache/node-gyp/15.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/saif/.cache/node-gyp/15.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/saif/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/saif/.cache/node-gyp/15.3.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/saif/.twilio-cli/runtime_modules/twilio-cli/node_modules/keytar',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package libsecret-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsecret-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsecret-1' found
gyp: Call to 'pkg-config --cflags libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/saif/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
gyp ERR! System Linux 5.4.0-53-generic
gyp ERR! command "/home/saif/.nvm/versions/node/v15.3.0/bin/node" "/home/saif/.nvm/versions/node/v15.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/saif/.twilio-cli/runtime_modules/twilio-cli/node_modules/keytar
gyp ERR! node -v v15.3.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
 » Secure credential storage failed to load.

Alternatively, twilio-cli can use credentials stored in environment variables:

# OPTION 1 (recommended)
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_API_KEY=an API Key created at twil.io/get-api-key
export TWILIO_API_SECRET=the secret for the API Key

# OPTION 2
export TWILIO_ACCOUNT_SID=your Account SID from twil.io/console
export TWILIO_AUTH_TOKEN=your Auth Token from twil.io/console

Once these environment variables are set, a twilio-cli profile is not required and you may skip the "login" step.
```

### Technical details:
* twilio-cli version: `twilio-cli/2.14.0` 
* node version: `v15.3.0`
* OS: `linux-x64`

**Comment by Rubix982** [comment]
Fixed! Please take a look at,
```
prebuild-install WARN install No prebuilt binaries found (target=15.3.0 runtime=node arch=x64 libc= platform=linux)
```

I was using nodejs with a version `15.3.0`. Since it did not have any predbuilt binaries for `twilio-cli` for that specific version, I ran,
```bash
$ nvm install --lts
$ nvm use --lts
```

And it gave me `node` with a version `14.15.1`. I then ran `npm install -g twilio-cli`, and ran `twilio login`, and it worked fine perfectly. 

Thank you!
