### ISSUE TITLE
when I use cli to deploy my app to video serverless service, server give me 20001 error

### ISSUE THREAD

**Issue by wangchengyu** [twilio/twilio-cli#252]
## command: 
```
twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build --override
```

## error message
```
Something went wrong ClientApiError [TwilioApiError]: unsupported runtime: node10
    at Object.convertApiErrorsAndThrow (/home/ec2-user/.twilio-cli/node_modules/@twilio-labs/serverless-api/dist/utils/error.js:31:15)
    at TwilioServerlessApiClient.<anonymous> (/home/ec2-user/.twilio-cli/node_modules/@twilio-labs/serverless-api/dist/client.js:392:25)
    at Generator.throw (<anonymous>)
    at rejected (/home/ec2-user/.twilio-cli/node_modules/@twilio-labs/serverless-api/dist/client.js:7:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 20001,
  details: {
    code: 20001,
    message: 'unsupported runtime: node10',
    more_info: 'https://www.twilio.com/docs/errors/20001',
    status: 400,
    request_url: 'https://serverless.twilio.com/v1/Services/ZSxxxxxxxxxxxxxxxxx/Builds'
  }
}
Web App URL: https://video-app-1718-6875-dev.twil.io?passcode=123456789
Passcode: 
Expires: Mon May 10 2021 03:22:17 GMT+0000
Room Type: group
Edit your token server at: https://www.twilio.com/console/functions/editor/ZSdexxxxxxxxxxxxx/environment/ZEdexxxxxxxxxxxxx/function/ZHxxxxxxxxxxxxx
deploying app... done
```

**Comment by JenniferMah** [comment]
Hi @wangchengyu 
It looks like serverless toolkit [no longer supports node 10](https://github.com/twilio-labs/serverless-toolkit/pull/253). Please try upgrading to node 12 or newer. If you have anymore questions while running this plugin command, please open an issue over in [twilio-labs/plugin-rtc](https://github.com/twilio-labs/plugin-rtc/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

**Comment by wangchengyu** [comment]
Thank you very much!
