### ISSUE TITLE
twilio-cli: twilio phone-numbers:list returns unexpected error

### ISSUE THREAD

**Issue by StephenUlm** [twilio/twilio-cli#263]
whenever I execute this command:  twilio phone-numbers:list, I get an unexpected error.  Error states accountSid must start with AC, and it does, so not sure why it is not reading it correctly.  DEBUG found below.

[DEBUG] Found command "phone-numbers:list" plugin: twilio-cli
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio/twilio-cli/issues"
[DEBUG] accountSid must start with AC
[DEBUG] Error: accountSid must start with AC
    at new Twilio (C:\Users\testuser\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\twilio\lib\rest\Twilio.js:142:11)
    at new initializer (C:\Users\testuser\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\twilio\lib\index.js:10:10)
    at NumberList.buildClient (C:\Users\testuser\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@twilio\cli-core\src\base-commands\twilio-client-command.js:129:12)
    at NumberList.get twilioClient [as twilioClient] (C:\Users\testuser\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@twilio\cli-core\src\base-commands\twilio-client-command.js:116:26)
    at NumberList.run (C:\Users\testuser\AppData\Roaming\npm\node_modules\twilio-cli\src\commands\phone-numbers\list.js:7:33)
    at async NumberList._run (C:\Users\testuser\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@oclif\command\lib\command.js:43:20)
    at async Config.runCommand (C:\Users\testuser\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@oclif\config\lib\config.js:173:24)
    at async Main.run (C:\Users\testuser\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@oclif\command\lib\main.js:27:9)
    at async Main._run (C:\Users\testuser\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@oclif\command\lib\command.js:43:20)

**Comment by onuzbee** [comment]
Thanks for reaching out @StephenUlm . 
From the logs, there seems to be a malformed accountSid stored in config. Could you try the following and let us know if it works? 

- Reconfigure the current profile, using `twilio profiles:create` and rerun the command using `twilio phone-numbers:list -p "new_added_profile" `
- In case step 1 doesn't work, Recheck node version installed > `12.21 ` and update cli installation: `npm install twilio-cli@latest -g`. For more details refer [here](https://www.twilio.com/docs/twilio-cli/quickstart) and retry back the step 1.
