### ISSUE TITLE
Fail to install @twilio-labs/plugin-flex plugin

### ISSUE THREAD

**Issue by OrRosenblatt** [twilio/twilio-cli#546]
### Issue Summary
Fail to install `@twilio-labs/plugin-flex` plugin after upgrading Twilio CLI version. Tried uninstall and installing, and the plugin still fails to install. 

### Code Snippet
```node
brew tap twilio/brew && brew install twilio
twilio login
twilio profiles:use my_twilio_account
twilio plugins:install @twilio-labs/plugin-flex
```

### Exception
```log
% twilio plugins:install @twilio-labs/plugin-flex
 » If you're using autocomplete, you'll need to run twilio autocomplete after installing a plugin and then open a new terminal window. The CLI needs to re-build its cache.
Installing plugin @twilio-labs/plugin-flex... failed
    Error: yarn add @twilio-labs/plugin-flex@latest --non-interactive --mutex=file:/Users/my.user/.twilio-cli/yarn.lock 
    --preferred-cache-folder=/Users/my.user/.twilio-cli/yarn --check-files exited with code 1
% 
```

### Error Log
```log
023-07-12T15:37:35.586Z Error: Missing 1 required arg:
2023-07-12T15:37:35.586Z profile  Shorthand identifier for your profile
2023-07-12T15:37:35.586Z See more help with --help
2023-07-12T15:37:35.586Z     at validateArgs (/usr/local/Cellar/twilio/5.10.0/libexec/node_modules/@oclif/core/lib/parser/validate.js:29:19)
2023-07-12T15:37:35.586Z     at Object.validate (/usr/local/Cellar/twilio/5.10.0/libexec/node_modules/@oclif/core/lib/parser/validate.js:153:5)
2023-07-12T15:37:35.586Z     at Object.parse (/usr/local/Cellar/twilio/5.10.0/libexec/node_modules/@oclif/core/lib/parser/index.js:30:13)
2023-07-12T15:37:35.586Z     at async ProfilesUse.parse (/usr/local/Cellar/twilio/5.10.0/libexec/node_modules/@oclif/core/lib/command.js:166:25)
2023-07-12T15:37:35.586Z     at async ProfilesUse.run (/usr/local/Cellar/twilio/5.10.0/libexec/node_modules/@twilio/cli-core/src/base-commands/base-command.js:33:29)
2023-07-12T15:37:35.586Z     at async ProfilesUse.run (/usr/local/Cellar/twilio/5.10.0/libexec/src/commands/profiles/use.js:6:5)
2023-07-12T15:37:35.586Z     at async ProfilesUse._run (/usr/local/Cellar/twilio/5.10.0/libexec/node_modules/@oclif/core/lib/command.js:80:22)
2023-07-12T15:37:35.586Z     at async Config.runCommand (/usr/local/Cellar/twilio/5.10.0/libexec/node_modules/@oclif/core/lib/config/config.js:301:25) 
````

### Technical details:
* twilio-cli version: `twilio-cli/5.10.0 darwin-x64 node-v18.16.1`
* node version: `18.16.1`
* Command output with debug logging enabled (adding `-l debug` to the end of the command):
```
# paste output here
```

**Comment by AsabuHere** [comment]
I tried the same steps with same version of twilio and node and here's what I got . Can you please share the machine in which you are trying this?
<img width="1193" alt="Screenshot 2023-07-13 at 2 49 04 PM" src="https://github.com/twilio/twilio-cli/assets/102021496/3a3bb8fc-6ce9-4dba-9bbd-88d7254b7f1a">

**Comment by tecoad** [comment]
@OrRosenblatt I have same issue. Can you share the solution?
